name: Deploy to EC2

on:
  push:
    branches:
      - master


jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: 152.58.16.206
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: whoami
